modLoader="javafml"
loaderVersion="[14,)"
license="MIT"

[[mods]]
modId="sqlconnectors"
version="${file.jarVersion}"
displayName="Forge SQL Connectors"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/Tagnum-Mods/SQLConnectors"
credits=""
authors="TagnumElite"
description=''''''

[[dependencies.sqlconnectors]]
    modId="dynmap"
    mandatory=false
    versionRange="[3,)"
    ordering="BEFORE"
    side="SERVER"

[[dependencies.sqlconnectors]]
    modId="forge"
    mandatory=true
    versionRange="[14,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sqlconnectors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.12,)"
    ordering="NONE"
    side="BOTH"
